apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prime-spark

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

# Staging-specific patches
patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml

configMapGenerator:
  - name: kva-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=staging

images:
  - name: prime-spark/kva-api
    newTag: staging-latest
