apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - deployment-kva-api.yaml
  - service.yaml
  - hpa.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: prime-spark-ai
  app.kubernetes.io/managed-by: kustomize
