apiVersion: v1
kind: Service
metadata:
  name: kva-api
  namespace: prime-spark
  labels:
    app: kva-api
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: http
    protocol: TCP
    name: http
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: kva-api
---
apiVersion: v1
kind: Service
metadata:
  name: kva-api-headless
  namespace: prime-spark
  labels:
    app: kva-api
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8002
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: kva-api
